# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad18f5345fe0d1cef27ab0942bbda5cdc88114d96600931ae00b875464f634c88fcdc860e82db2207827fe6749837e35c336b608f117e76eaf2b0f3c6070e153

test:
  secret_key_base: 7a1fad5a7b729099a1cc60b2d9d33aaaafd65e18c39c36135ec3cffeb2e7db118e2f0d2da0e7274c6bb1561d919d369cc82723db1c62c8531d9ed142d46fb370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
